index:
  path: /
  controller: App\Controller\MainController::index

info:
  path: /{_locale}/muy-importante-info
  controller: App\Controller\MainController::info
  requirements:
    _locale: en|es


map:
  path: /map
  controller: App\Controller\MainController::map
  #prefix: /admin2  # require 'composer require symfony/annotacion' 
  #trailing_slash_on_root: false

# Para mail
app_email:
  path: /email
  controller: App\Controller\MainController::email
app_email2:
  path: /email2
  controller: App\Controller\MainController::email_template  

# Subscribe
app_subscribe:  
  path: /subscribe
  controller: App\Controller\MainController::subscribe

# Lucky
lucky:
  path: /lucky/
  controller: App\Controller\LuckyController::index
app_lucky_number:
  path: /lucky/number/
  controller: App\Controller\LuckyController::randomNumber
app_lucky_frase:
  path: /lucky/frase/
  controller: App\Controller\LuckyController::randomFrase

# Login
login:
  path:       /login
  controller: App\Controller\AuthController::login
  methods:    GET
# Register
register:
  path:       /registrarse
  controller: App\Controller\AuthController::register
  methods:    GET 
# Logout 
logout: 
  path:       /logout
  controller: App\Controller\AuthController::logout
  methods:    GET   

# API
api_post_index:
  path:       /api/v1.2/posts
  controller: App\Controller\Api\BlogController::index
  methods:    GET
    
api_post_show:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::show
  methods:    GET|HEAD

api_post_edit:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::edit
  methods:    PUT

# Products
products_index:
  path: /products/
  controller: App\Controller\ProductController::index  

# Animals
animals_index:
  path: /animals
  controller: App\Controller\AnimalsController::index
  methods: GET
animals_show:
  path: /animals/show/{id}
  controller: App\Controller\AnimalsController::show
  methods: GET
animals_add:
  path: /animals/add
  controller: App\Controller\AnimalsController::add
  methods: POST|GET 
animals_edit:
  path: /animals/edit/{id}
  controller: App\Controller\AnimalsController::edit
  methods: POST|GET 
animals_delete:
  path: /animals/delete/{id}
  controller: App\Controller\AnimalsController::delete
  methods: POST|GET 

# Paciente
paciente_index:
  path: /pacientes
  controller: App\Controller\PacienteController::index
  methods: GET
paciente_add:
  path: /pacientes/add
  controller: App\Controller\PacienteController::add
  methods: POST|GET
paciente_show:
  path: /pacientes/show/{id}
  controller: App\Controller\PacienteController::show
  methods: POST|GET
paciente_edit:
  path: /pacientes/edit/{id}
  controller: App\Controller\PacienteController::edit
  methods: POST|GET
 
# Doctor 
doctor_index:
  path: /doctors
  controller: App\Controller\DoctorController::index
  methods: GET
doctor_add:
  path: /doctors/add
  controller: App\Controller\DoctorController::add
  methods: POST|GET 
doctor_show:
  path: /doctors/show/{id}
  controller: App\Controller\DoctorController::show
  methods: POST|GET 
doctor_edit:
  path: /doctors/edit/{id}
  controller: App\Controller\DoctorController::edit
  methods: POST|GET     
doctor_lista:
  path: /doctors/lista-de-pacientes/{id}
  controller: App\Controller\DoctorController::lista
  methods: GET 

# Cabinet - para doctor 
cabinet_index:
  path:       /cabinet
  controller: App\Controller\CabinetController::index
  methods:    GET 
cabinet_pacientes:
  path: /cabinet/pacientes
  controller: App\Controller\CabinetController::pacientes
  methods: GET   

# Dashboard - para paciente  
dashboard_index: 
  path: /dashboard 
  controller: App\Controller\DashboardController::index 
  methods: GET 
dashboard_doctors:
  path: /dashboard/doctors
  controller: App\Controller\DashboardController::doctors
  methods: GET 
dashboard_anketa:
  path: /dashboard/anketa
  controller: App\Controller\DashboardController::anketa
  methods: GET|POST   


# Lead
lead_index:
  path: /leads
  controller: App\Controller\LeadController::index
  methods: GET 
lead_add:
  path: /leads/add
  controller: App\Controller\LeadController::add
  methods: POST|GET 
lead_show:
  path: /leads/show/{id}
  controller: App\Controller\LeadController::show
  methods: POST|GET 
lead_edit:
  path: /leads/edit/{id} 
  controller: App\Controller\LeadController::edit
  methods: POST|GET 

