#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Lucky
lucky:
  path: /lucky/
  controller: App\Controller\LuckyController::index

app_lucky_number:
  path: /lucky/number/
  controller: App\Controller\LuckyController::randomNumber

app_lucky_frase:
  path: /lucky/frase/
  controller: App\Controller\LuckyController::randomFrase

# Login
login:
  path: /login/
  controller: App\Controller\AuthController::login

# API
api_post_index:
  path:       /api/v1.2/posts
  controller: App\Controller\Api\BlogController::index
  methods:    GET
    
api_post_show:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::show
  methods:    GET|HEAD

api_post_edit:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::edit
  methods:    PUT

# Animals
animals_index:
  path: /animals
  controller: App\Controller\AnimalController::index
  methods: GET

animals_add:
  path: /animals/add
  controller: App\Controller\AnimalController::add
  methods: POST|GET 

animals_edit:
  path: /animals/edit/{id}
  controller: App\Controller\AnimalController::edit
  methods: POST|GET 

animals_delete:
  path: /animals/delete/{id}
  controller: App\Controller\AnimalController::delete
  methods: POST|GET 

# 

