index:
  path: /
  controller: App\Controller\MainController::index

info:
  path: /muy-importante-info
  controller: App\Controller\MainController::info

# Lucky
lucky:
  path: /lucky/
  controller: App\Controller\LuckyController::index

app_lucky_number:
  path: /lucky/number/
  controller: App\Controller\LuckyController::randomNumber

app_lucky_frase:
  path: /lucky/frase/
  controller: App\Controller\LuckyController::randomFrase

# Login
login:
  path: /login/
  controller: App\Controller\AuthController::login

# API
api_post_index:
  path:       /api/v1.2/posts
  controller: App\Controller\Api\BlogController::index
  methods:    GET
    
api_post_show:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::show
  methods:    GET|HEAD

api_post_edit:
  path:       /api/v1.2/posts/{id}
  controller: App\Controller\Api\BlogController::edit
  methods:    PUT

# Products
products_index:
  path: /products/
  controller: App\Controller\ProductController::index  

# Animals
animals_index:
  path: /animals
  controller: App\Controller\AnimalsController::index
  methods: GET

animals_show:
  path: /animals/show/{id}
  controller: App\Controller\AnimalsController::show
  methods: GET

animals_add:
  path: /animals/add
  controller: App\Controller\AnimalsController::add
  methods: POST|GET 

animals_edit:
  path: /animals/edit/{id}
  controller: App\Controller\AnimalsController::edit
  methods: POST|GET 

animals_delete:
  path: /animals/delete/{id}
  controller: App\Controller\AnimalsController::delete
  methods: POST|GET 

# Paciente
paciente_index:
  path: /pacientes
  controller: App\Controller\PacienteController::index
  methods: GET

paciente_add:
  path: /pacientes/add
  controller: App\Controller\PacienteController::add
  methods: POST|GET
  
paciente_show:
  path: /pacientes/show/{id}
  controller: App\Controller\PacienteController::show
  methods: POST|GET

paciente_edit:
  path: /pacientes/edit/{id}
  controller: App\Controller\PacienteController::edit
  methods: POST|GET

